### ISSUE TITLE
"Save file" on web ui tool makes "fs\init.js" files instead of replacing init.js in Windows

### ISSUE THREAD

**Issue by sahilkhanna** [cesanta/mongoose-os#386] opened 2017-11-23 02:48 UTC
I think this is more of a Windows directory path incompatibility issue. The web ui expects a "/" to consider it as another directory.

![image](https://user-images.githubusercontent.com/5364717/33157265-ffd55ad0-d054-11e7-9749-d94d41beb4c2.png)

Is there any workaround for this?

**Comment by dimonomid** [comment] 2017-12-12 17:48
Sorry, can't reproduce. On the "Device Files" tab, I open `init.js` file, then click "Save File" button, and `init.js` gets saved correctly. Which mos version do you use?

**Comment by sahilkhanna** [comment] 2017-12-13 01:32
I'm sorry, I think I forgot to add some info.
So the issue occurs when you save and copy files from "Projects" tab to the device and NOT on the "Device files" tab. The webui tool confuses with the window's directory naming structure and does not consider "fs\init.js" as a file called "init.js" in "fs" folder but rather treats the whole path "fs\init.js" as a file. This essentially has to do with the backward slash issue in webUI side of things.
FYI I tested this on 
Version: 1.20.1
Build ID: 20171117-113830/1.20.1@d0c3a61b+
OS: Windows 10
Browser: Chrome
but I think the issue still persists in the latest release of mos.exe.
I was able to to edit the .exe file using a hexeditor to essentially replace "\" with "/" which fixed my issue but its not an elegant fix.

**Comment by dimonomid** [comment] 2017-12-13 14:15
Hmm, and still can't reproduce. So I opened `fs\index.html`, clicked the "Save currently opened file" button, and `C:\Users\myuser\.mos\apps-1.20.1\empty-1.15\fs\index.html` file is updated correctly.

![image](https://user-images.githubusercontent.com/1329932/33942991-5e247708-e020-11e7-890f-54f0693cb607.png)

> I was able to to edit the .exe file using a hexeditor to essentially replace "" with "/" which fixed my issue but its not an elegant fix.

Wow that sounds hardcore, however from your explanation `replace "" with "/"` it's unclear what exactly did you replace with what. Also I assume there are plenty of `\` occurrences btw.

**Comment by sahilkhanna** [comment] 2017-12-13 23:15
The issue is not with the save, it's with the "save, copy to device and reboot"  button. Try that and then check your "Device Files" tab.
![image](https://user-images.githubusercontent.com/5364717/33967400-77ef5634-e0b7-11e7-91ea-296bd94a9c00.png)

**Comment by dimonomid** [comment] 2017-12-13 23:29
Finally it's clear now. :) Ok, I think I'll commit the fix tomorrow, thanks for reporting.

**Comment by dimonomid** [comment] 2017-12-14 21:54
Fixed in private repo, will be published soon.

**Closed** 2017-12-14 21:54 UTC
