### ISSUE TITLE
WPS support.

### ISSUE THREAD

**Issue by bestpika** [cesanta/mongoose-os#280] opened 2017-06-09 06:32 UTC
Could Mongoose OS add WPS support for ESP8266 and ESP32.
Thank you.

**Comment by cpq** [comment] 2017-06-15 11:17
Do you mean https://en.wikipedia.org/wiki/Wi-Fi_Protected_Setup ?
If yes, could you elaborate on your project please?

**Comment by bestpika** [comment] 2017-06-15 14:14
Yes, I mean Wi-Fi Protected Setup.
I wish my device have less setting and easy to use, so user no need to enter any information, they just press WPS button and my device can auto connect to Internet.

**Comment by scotthernandez** [comment] 2017-08-11 18:30
As stated in the wikipedia page this feature is no longer suggested for security reasons. It is not secure and should not be used -- is is broken by design and allows an attack vector for brute-force attacks to be successful in milliseconds, or a few hours at the most. Just having it enabled in the access point (router) open up this attack vector, even if never actually used.

**Comment by cpq** [comment] 2017-08-17 08:26
Good point, Scott.
Closing this.

**Closed by cpq** 2017-08-17 08:26 UTC
Labels: enhancement

**Comment by bestpika** [comment] 2017-08-18 01:59
If use push button method not pin mode, I think it still secure.

**Comment by kunal-cloud-kickers** [comment] 2018-11-08 06:54
Yes is it possible to push button on both end, from wifi router and esp?
