### ISSUE TITLE
Support RS485

### ISSUE THREAD

**Issue by tusharvb19** [cesanta/mongoose-os#308] opened 2017-07-05 07:19 UTC
I want to use modbus on mongoose-os.
I am using following hardware-
RS485 module using UART.
http://www.electrodragon.com/product/max485-rs-485-module-ttl-to-rs-485/

**Comment by tusharvb19** [comment] 2017-07-12 10:16
Is there anyone who can help me!

**Comment by cpq** [comment] 2017-07-15 14:26
Actually this is a duplicate of https://github.com/cesanta/mongoose-os/pull/256

**Closed by cpq** 2017-07-15 14:26 UTC
